# Generated by Django 4.1.7 on 2023-03-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="note",
            name="notes",
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
